Documentation revision
aiidalab/aiidalab pull request #150
Opened 2021-03-03 20:14 UTC by csadorf

2021-03-03 20:15 UTC, csadorf commented
@yakutovicha I found it easier to just create a PR into your instead of creating hundreds of comments. Once you have merged this, I can approve your PR.

2021-03-03 20:28 UTC, yakutovicha requested changes
thanks @csadorf. I found one little typo only

2021-03-03 20:28 UTC, yakutovicha commented on docs/source/deployment/index.rst
> +There are several ways one can deploy AiiDAlab: locally for onself, on a server for multiple users, or on a Kubernetes cluster for many users and high availability and scalability.
```suggestion
There are several ways one can deploy AiiDAlab: locally for oneself, on a server for multiple users, or on a Kubernetes cluster for many users and high availability and scalability.
```

2021-03-04 09:59 UTC, yakutovicha approved these changes

2021-03-04 10:19 UTC, merged