Fix base.html URLs
aiidalab/aiidalab pull request #379
Opened 2023-03-22 06:59 UTC by Mahhheshh

Solves #371 
Updated the URLs used in the footer of the application to use the correct links. Previously, the links were pointing to the wrong resources, but have been updated to point to the correct URLs. This includes updating the links to the AiiDAlab registry page in the aiidalab-registry repository. These changes ensure that users can access the correct resources from the footer of the application.

This pull request fixes an issue in the parent file `base.html` at https://github.com/aiidalab/aiidalab/blob/50498b08ea77937cb8af0e8d753446dd17b6d637/aiidalab/registry/templates/base.html#L3 which was causing issues in the child file `layout.html` at https://github.com/aiidalab/aiidalab-registry/blob/8bc5d00fffa2016f562d065d81bd5a111c99479e/src/templates/layout.html#L8. The issue was causing variables to not be overwritten in the registry repository. The changes made in this pull request fix the links in the footer, and ensure that the variables can be correctly overwritten in the child file.

2023-03-22 19:41 UTC, yakutovicha requested changes
thanks, @Mahhheshh. Could you also fix the links in: `docs/source/conf.py` and `docs/source/usage/index.rst`? They still point to the old AiiDAlab URL.

2023-03-23 16:04 UTC, yakutovicha commented
> Yes, are there any additional links I'm missing?

I think that is all.

2023-03-23 16:45 UTC, yakutovicha requested changes
Thanks, just a few small changes.

2023-03-23 16:45 UTC, yakutovicha commented on docs/source/usage/index.rst
> + 1. Log into one of the `open AiiDAlab servers <https://www.aiidalab.net/>`_.
```suggestion
 1. Log into one of the `open AiiDAlab servers <https://www.aiidalab.net/deployments/>`_.
```

2023-03-23 16:45 UTC, yakutovicha commented on Pipfile
> +[[source]]
I don't think this file is needed.

2023-03-23 16:55 UTC, Mahhheshh commented on Pipfile
> +[[source]]
Sorry for that I will remove it

2023-03-23 18:54 UTC, yakutovicha approved these changes

2023-03-23 18:57 UTC, merged